### PR TITLE
Update `purescript` dep to 0.15.0

### PR DESCRIPTION
**Pull request by JordanMartinez**
I tried regenerating the `LICENSE` file but don't have https://hackage.haskell.org/package/cabal-dependency-licenses installed. I'll need to figure that out before we merge and redeploy this.

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Actually, it looks like that license library is no longer maintained, but [it does recommend an alternative](https://github.com/jaspervdj/cabal-dependency-licenses#cabal-dependency-licenses=): 

[cabal-plan](https://hackage.haskell.org/package/cabal-plan#description)

**Review by thomashoneyman — APPROVED** [review]

**Comment by JordanMartinez** [comment]
@hdgarrood Just a few questions...
- are my license generation changes valid? I couldn't get `cabal-dependency-licenses` to build, so I had to use `cabal-plan`.
- do we still need the LGPL section?

**Comment by hdgarrood** [comment]
The changes to LICENSE seem reasonable to me. If we aren’t depending on anything that’s LGPL any more then I think we can get rid of that section.

**Comment by JordanMartinez** [comment]
Cool. I'll get rid of it.

**Comment by JordanMartinez** [comment]
Pursuit has now been deployed.

**Pull request merged**
