### PR TITLE
Add section to Pursuit help page about updating packages.

### LINKED ISSUE #172: "How to submit packages" section on Pursuit should have a section about submitting new versions of packages
It would be nice if there was a section on updating packages on Pursuit's [help](http://pursuit.purescript.org/help) page.

As a new user, when I want to update a package I've previously released, I'm not sure whether I need to upload a new `pursuit.json` file, or if I just need to push a new tag to Github (similar to how bower packages work).

It would be nice if there was a section on the help page explaining this.

### PR DESCRIPTION
**Pull request by cdepillabout**
Add steps for updating packages.

Closes #172.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Is updating really simpler than creating? I'm not sure it is. Also I'd rather not have all the steps duplicated, can you just write something like "the same, except of course you don't need to `bower register` again"?

**Comment by cdepillabout** [comment]
Okay, I simplified the help text in commit 074daf7.  How does it sound now?

**Comment by hdgarrood** [comment]
Looks good. Thanks!

**Comment by paf31** [comment]
:+1:

**Pull request merged**
