### PR TITLE
Include library web urls in generated data

### PR DESCRIPTION
**Pull request by hdgarrood**
This PR updates the structure of libraries.json (as in #6) as well as updating the generator so that each library's web url is available to the client, in the generated `data.json`.

### CODE REVIEW

**Comment by hdgarrood** [comment]
At the moment, the client doesn't use any of this newly available data - I'll look into that after this is merged.

**Comment by paf31** [comment]
This looks good, and I'm happy to merge now.

However, I'm thinking of turning Pursuit into a fully server-side application, combining the current search with the `psc-pages` generated documentation. I feel like this will make it easier to implement things like type-based search.

I was going to create an issue to discuss this today, but got sidetracked, but I would definitely like to discuss this with you.

Given that, I think this is still useful (we'll still want this data available), but I'm not sure how it fits in with a rewrite.

Let me know what you think.

**Comment by hdgarrood** [comment]
Sounds good to me. I'm having a little difficulty picturing how it would all go together, though. Are you picturing something like Hackage? Would the process of adding a library remain the same - that is, a PR modifying libraries.json?

**Comment by paf31** [comment]
Yes, I was thinking that the app would include your Git logic, and the current Cron job would just be a timer which reran the job and updated a `TVar` containing the database or something similar. We could also use Postgres or something similar, but I'm not sure that's necessary.

The app would not create `data.json`, but would still load and process `libraries.json`.

**Comment by hdgarrood** [comment]
Ok, cool. In that case, if I've understood correctly, I think most of the code in this PR wouldn't need to change.

How do you think we should progress now?

**Comment by paf31** [comment]
Let's start an issue to discuss the new design. I'll write something up tomorrow.

I expect this will make things simpler, since we'll only have one code base to work on, but we'll see.

If you're on IRC this week, maybe we can discuss there too.

**Comment by pelotom** [comment]
Just a voice from the peanut gallery, but it would be really cool to have this feature in the deployed version while you're busy refactoring things :grin:

**Comment by paf31** [comment]
I'll deploy this now.

**Comment by paf31** [comment]
@pelotom @hdgarrood This is now running on pursuit.purescript.org.

**Comment by pelotom** [comment]
Thanks! I take it there are still changes needed on the front-end to get links to appear in search results?

**Comment by paf31** [comment]
Yes, but it's pretty simple. I can take a look.

**Comment by paf31** [comment]
Done.

**Comment by pelotom** [comment]
I see the library name now but it doesn't appear to be a link...?

**Comment by pelotom** [comment]
Not that that's really needed, I suppose... this is great! :+1:

**Comment by paf31** [comment]
Well, the client doesn't get the link, right now. I could link to Bower, I guess?

**Comment by pelotom** [comment]
Nah, I don't think that's necessary :)

**Pull request merged**
