### PR TITLE
search: promote exact type matches

### PR DESCRIPTION
**Pull request by matthewleon**
addresses #132

(Data.String.singleton should be the first result for the query "Char -> String")

This is probably not the ideal solution to the issue, but in lieu of an overhauled type matching algorithm, it seems to work as a pragmatic stopgap.

### CODE REVIEW

**Comment by hdgarrood** [comment]
The type matching algorithm isn't particularly complicated right now, so I'd prefer to do it properly - which means first finding out exactly why `Char -> String` doesn't give `singleton` the highest score. Have you been able to work out why that is?

**Comment by matthewleon** [comment]
It does give singleton the highest score, which is zero, for a complete match. It just gives a whole lot of other things a zero as well, and then sorts alphabetically.

I can go have another look to establish a more type-based way to "punish" everything that isn't an _exact_ type match by raising its score. That is, indeed, the proper way to do it.

That said, even if I were to do that, is there any actual harm in raising the score of everything that doesn't have a string type match? It seems to me that, at the very least, it can act as a "safety net" to ensure that even if there is a flaw in our logic that we don't figure out, the match the user is looking for gets a fighting chance of making it to the top.

A hack, admittedly, but I think it's a very pragmatic one.

**Comment by hdgarrood** [comment]
To be able to convincingly argue that it's pragmatic, we'd first need to establish that doing it properly is prohibitively expensive; that hasn't happened yet as far as I can see.

**Comment by matthewleon** [comment]
I'll give it another shot.

**Comment by hdgarrood** [comment]
Thanks :smile:

**Pull request closed without merging**
