### PR TITLE
Use barrier to generate badges

### LINKED ISSUE #102: Use shields.io for badges
I can't quite work out what it is, but the badges that pursuit currently renders just don't quite look right. Eg: http://new-pursuit.purescript.org/packages/purescript-thermite/0.8.0

### PR DESCRIPTION
**Pull request by tfausak**
This fixes #102.

I decided to use barrier because it's what Stackage uses. Check out [their badge handler](https://github.com/fpco/stackage-server/blob/ade312b9dfa98db27f2eca68c15b75036ce128c1/Handler/Package.hs#L53) to see how it works.

### CODE REVIEW

**Comment by tfausak** [comment]
Almost forgot to post screenshots! Before:

screen shot 2016-05-01 at 6 54 25 am

After:

screen shot 2016-05-01 at 6 52 53 am

**Comment by hdgarrood** [comment]
Looks great :)

Just one thing: I think I'd rather use the `renderBadge` function, since then I don't think we need to import the `Internal` module. Then I think you can use `preEscapedToMarkup` to turn the `ByteString` into `Svg`.

**Comment by tfausak** [comment]
👍 I had to use [`unsafeLazyByteString`](http://haddock.stackage.org/lts-5.14/blaze-markup-0.7.0.3/Text-Blaze.html#v:unsafeLazyByteString) instead of `preEscapedToMarkup` because there's no `ByteString` instance for `ToMarkup`.

**Comment by hdgarrood** [comment]
Looks great, thanks!

**Pull request merged**
