### PR TITLE
Add "/" as a global search-input focus shortcut

### PR DESCRIPTION
**Pull request by spicydonuts**

### CODE REVIEW

**Comment by hdgarrood** [comment]
Thanks for the contribution, but I'm not very keen on this, given that Firefox already uses that key for a quick search feature.

**Comment by hdgarrood** [comment]
(That's why I chose S in the first place, even.)

**Comment by spicydonuts** [comment]
Ah, I didn't know that.  Like Ctrl+F search?  Just used to "/" in most tools : ] (vim, less, twitter).

**Comment by hdgarrood** [comment]
Yeah, it's similar to that. Not sure why they needed two but there you go

**Comment by spicydonuts** [comment]
(just discovered npmjs.org uses "/" too : ]  )

**Comment by michaelficarra** [comment]
Yeah, a lot of websites use `/`. But as a counter-example, GitHub uses `s`.

**Pull request closed without merging**
