### PR TITLE
Added a bunch of libraries.

### PR DESCRIPTION
**Pull request by joneshf**
Finally got around to adding some of my libraries. Let me know if I did this incorrectly.

Also, now that things have changed, what's the prefered way of adding a library? How can we test that things didn't break? I run `cat libraries.json | ./dist/build/pursuit-gen/pursuit-gen -o data.json` and then `./dist/build/pursuit-server/pursuit-server` and can then curl stuff, so I assume it works. But, I can't figure out how the client is supposed to work with that.

### CODE REVIEW

**Comment by paf31** [comment]
Let's see... :)

**Comment by paf31** [comment]
I just ran the job by hand, and it looks like it's working.

http://pursuit.purescript.org/?(.~)

/cc @hdgarrood

**Comment by hdgarrood** [comment]
Maybe we could have a Travis CI job that attempts the first of the above commands? If the it exits with 0, I think there's a pretty good chance it's been done correctly.

**Comment by paf31** [comment]
Well, the script already bails out if the generator fails, so I think it's doing the same job, but CI couldn't hurt.

**Comment by hdgarrood** [comment]
We can ask Travis to run builds on each PR so this could work rather nicely

**Comment by hdgarrood** [comment]
Yes - the benefit with Travis would be that a) the submitter gets a notification that the build failed, and b) there's a much lower chance of jobs on the VM failing because of a mistake.

**Comment by joneshf** [comment]
Thanks!

**Pull request merged**
