### PR TITLE
Add margins to highlighted code blocks

### PR DESCRIPTION
**Pull request by owickstrom**
This PR adds a top and bottom margin to `.highlight` blocks, with the same margin size as paragraphs. Without it, adjacent code blocks look like a single code block (in the example below this becomes confusing).

Note that I haven't set up Pursuit on my machine fully, and thus couldn't test this styling locally. I've just tested it in the Chrome inspector before making the changes, so someone might want to run this locally and verify on a few other READMEs.

## Before

image

## After

image

### CODE REVIEW

**Comment by hdgarrood** [comment]
I agree that I'd like to fix this, but I'm a little apprehensive about doing it like this because:

* If the same issue exists in API docs, i.e. for adjacent code blocks in doc-comments, I'd like to fix it there too
* I want to stop using the GitHub API for rendering readmes, and IIRC it's because of the GitHub API that these code blocks have a `highlight` class.

Did you have difficulty getting Pursuit working locally? I'd prefer this were more thoroughly tested first too.

**Comment by owickstrom** [comment]
I see!

I'll first try to get Pursuit up and running locally. The reason I didn't before was just lack of time, I squeezed this in before work. Then perhaps I might find some time to try an alternative to the GitHub API rendering. Do you have any other recommendations on what could be used? Maybe Pandoc?

**Comment by hdgarrood** [comment]
We are already using Cheapskate for doc-comments, so that would be the obvious choice. However, for the time being, the only way of getting the readme will be via the GitHub API, as currently it's not included in the json produced by purs publish. For now we could probably change the GitHub API call to ask for the raw README rather than rendered HTML, and then render it ourselves using Cheapskate. We would also have to work out how to handle the case where someone's README isn't Markdown.

**Comment by hdgarrood** [comment]
You might want to take a look at the discussion in https://github.com/purescript/pursuit/issues/150 for context, as well.

**Comment by hdgarrood** [comment]
I think I'll close this for now since there's been no movement for a while, but in general I'm happy to discuss changes like this (provided the above questions I raised have been addressed). Also, just FYI, I'm planning to change Pursuit soon so that it uses the CSS from the purescript library, so changes like this might need to be made there rather than here in the future.

**Pull request closed without merging**
