### PR TITLE
Fix badge cache invalidation (refs #162)

### PR DESCRIPTION
**Pull request by hdgarrood**
Ensure cached versions of package badges are invalidated properly. Partial fix for #162.

### CODE REVIEW

**Comment by paf31** [comment]
Why is this only a partial fix? What remains to be fixed?

**Comment by hdgarrood** [comment]
The 404 for http://pursuit.purescript.org/packages/purescript-websocket-simple/badge is still unexplained.

**Comment by paf31** [comment]
I don't get a 404 there any more. Was this before I cleared the cache?

**Comment by hdgarrood** [comment]
Um, I'm not sure. What does "this" mean in this context?

**Comment by paf31** [comment]
The 404. I'm a bit lost here, is there still an issue that we know of?

**Comment by hdgarrood** [comment]
Yeah I don't know. I guess you could try reproducing it by deleting the entire cache for purescript-websocket-simple and trying to GET the badge again. If that doesn't reproduce it then maybe we can just give up for now and hope it doesn't happen again.

**Pull request merged**
