### PR TITLE
Ensure only exported values are included in results

### PR DESCRIPTION
**Pull request by hdgarrood**
refs #1 

I think this will work, but it doesn't compile at the moment; it uses a couple of functions which are in the master branch of purescript, but not yet in any released version.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Is this resolved? I can still see `getCanvasElementById` on the live site, for example

**Comment by paf31** [comment]
No I need to release the purescript library I think.

**Comment by paf31** [comment]
Hmm, I didn't mean to close it. Are you able to reopen it?

**Comment by hdgarrood** [comment]
I don't think I am. Perhaps I could submit this again as a new PR?

**Comment by paf31** [comment]
Yes, sorry I think you might need to.

**Comment by hdgarrood** [comment]
No problem :)

**Pull request closed without merging**
