### PR TITLE
Get rid of the obsolete sample-data directory.

### LINKED ISSUE #194: Get rid of the obsolete sample-data directory
`submit-all` script fails with the following error messages:

```
$ ./sample-data/submit-all
{"error":["At the path: [\"modules\"][0][\"declarations\"][0][\"children\"][2][\"info\"][\"type\"]","Arising from an Aeson FromJSON instance:","When parsing the constructor Language.PureScript.Names.Qualified of type Qualified expected Array but got String."]}sending: ./sample-data/prelude-999.0.2.json
{"error":["At the path: [\"modules\"][0][\"declarations\"][0][\"children\"][0][\"info\"][\"type\"]","Arising from an Aeson FromJSON instance:","When parsing the constructor Language.PureScript.Names.Qualified of type Qualified expected Array but got String."]}sending: ./sample-data/quickcheck-999.0.0.json
{"error":["At the path: [\"modules\"][0][\"declarations\"][0][\"info\"][\"type\"]","Arising from an Aeson FromJSON instance:","When parsing the constructor Language.PureScript.Names.Qualified of type Qualified expected Array but got String."]}
```

### PR DESCRIPTION
**Pull request by kseo**
It is easier to clone https://github.com/purescript/pursuit-backups and put the
packages under data/verified directory instead of uploading the packages
manually using submit-all script. Fixes #194.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Thanks! Could you add a note to the README too, please?

**Comment by kseo** [comment]
Okay. I added "Database setup" section to README.

**Comment by hdgarrood** [comment]
Looks great, just one nit: could you write "you can clone *the* pursuit-backups repo" instead of "you can clone pursuit-backups repo"?

**Comment by kseo** [comment]
Sure! Done.

**Comment by hdgarrood** [comment]
:+1: thank you!

**Pull request merged**
